on: [push, pull_request]
name: Build

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
  
    - uses: actions/checkout@v3
    - run: go build -v

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          porncpy*